# Generated by Django 5.2.10 on 2026-01-21 23:08

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("gt", "Greater Than (>)"),
                            ("lt", "Less Than (<)"),
                            ("gte", "Greater Than or Equal (>=)"),
                            ("lte", "Less Than or Equal (<=)"),
                            ("eq", "Equal (=)"),
                            ("neq", "Not Equal (!=)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("threshold", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "action_config",
                    models.JSONField(
                        help_text='Schema: [{"type": "notification", "template_id": 5}, {"type": "stop_machine", "machine_id": "M-123"}]'
                    ),
                ),
                ("cooldown_minutes", models.IntegerField(default=15)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "rules",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "is_enabled"], name="idx_rule_device_enabled"
                    ),
                    models.Index(fields=["is_enabled"], name="idx_rule_is_enabled"),
                    models.Index(
                        fields=["last_triggered_at"], name="idx_rule_last_triggered"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["action_config"], name="idx_rule_action_config_gin"
                    ),
                ],
            },
        ),
    ]
