# Generated by Django 5.2.10 on 2026-01-22 12:20

import apps.rules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rule",
            old_name="operator",
            new_name="comparison_operator",
        ),
        migrations.AlterField(
            model_name="rule",
            name="action_config",
            field=models.JSONField(
                help_text='Schema: [{"type": "notification", "template_id": 5}, {"type": "stop_machine", "machine_id": "M-123"}]',
                validators=[apps.rules.models.validate_action_config],
            ),
        ),
    ]
