# Generated by Django 5.2.10 on 2026-01-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_rename_operator_to_comparison_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='cooldown_minutes',
        ),
    ]
