# Generated by Django 5.2.10 on 2026-02-02 08:38

import apps.rules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0004_telemetrycursor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="comparison_operator",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="threshold",
        ),
        migrations.AddField(
            model_name="rule",
            name="condition",
            field=models.JSONField(
                default=None,
                help_text='Schema: {"type": "leaf", "operator": "gt", "threshold": 15.2}',
                validators=[apps.rules.models.validate_condition],
            ),
            preserve_default=False,
        ),
    ]
