# Generated by Django 5.2.10 on 2026-02-19 12:30

import apps.rules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0005_remove_rule_comparison_operator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="condition",
            field=models.JSONField(
                help_text='Schema: [{"type": "notification", "template_id": 5}, {"type": "stop_machine", "machine_id": "M-123"}]',
                validators=[apps.rules.models.validate_condition],
            ),
        ),
    ]
