# Generated by Django 5.2.10 on 2026-03-05 10:54

import apps.rules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0009_ruleauditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="condition",
            field=models.JSONField(
                help_text='Schema: [{{"type": "leaf", "operator": "gt", "threshold": 25.5, "occurrences": 3, "window_seconds": 60}]',
                validators=[apps.rules.models.validate_condition],
            ),
        ),
    ]
