global:
  resolve_timeout: 5m

route:
  receiver: 'email'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h

receivers:
  - name: 'email'
    email_configs:
      - to: 'admin@iot-hub.local'
        from: 'alerts@iot-hub.local'
        smarthost: 'localhost:25'
        require_tls: false
        html: true
