services:
  web:
    volumes:
      - ./backend:/app
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
  worker:
    volumes:
      - ./backend:/app
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
  migrate:
    volumes:
      - backend-migrate-data:/app
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
  mqtt_adapter:
    volumes:
      - ./backend:/app
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
  db-writer:
    volumes:
      - ./backend:/app
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
  events_consumer:
    volumes:
      - ./backend:/app
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
volumes:
  backend-worker-data:
  backend-migrate-data:
