# server {
#     listen 80;
#     server_name localhost;

#     location /apt/ {
#         root /repo;
#         autoindex on;
#         auth_basic "Restricted Repository";
#         auth_basic_user_file /repo/auth/.htpasswd;
#     }

#     error_log /var/log/nginx/error.log warn;
#     access_log /var/log/nginx/access.log;
# }

server {
    listen 80;
    server_name localhost;

    auth_basic "Restricted Repo";
    auth_basic_user_file /repo/auth/.htpasswd;

    location /apt/ {
        alias /repo/apt/;
        autoindex on;
    }
}
