# Generated by Django 5.2.10 on 2026-01-21 23:08

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "message_template",
                    models.TextField(
                        help_text='Template with placeholders: "Alert {severity}: {message}"'
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        help_text='Schema: [{"type": "email", "address": "admin@company.com"}, {"type": "sms", "phone": "+380501234567"}]'
                    ),
                ),
                ("priority", models.IntegerField(default=1)),
                ("retry_count", models.IntegerField(default=3)),
                ("retry_delay_minutes", models.IntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_templates",
                "ordering": ["priority", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="idx_notif_templ_name"),
                    models.Index(fields=["is_active"], name="idx_notif_templ_active"),
                    models.Index(fields=["priority"], name="idx_notif_templ_priority"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["recipients"], name="idx_notif_templ_recip_gin"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recipient_address",
                    models.TextField(
                        help_text="Email address, phone number, or webhook URL"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rendered_message",
                    models.TextField(help_text="Actual message sent (snapshot)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=1)),
                ("attempt_count", models.IntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error details if status = failed",
                        null=True,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_deliveries",
                        to="events.event",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notification deliveries",
                "db_table": "notification_deliveries",
                "ordering": ["status", "priority", "-created_at"],
                "indexes": [
                    models.Index(fields=["event"], name="idx_notif_deliv_event"),
                    models.Index(
                        fields=["status", "priority", "created_at"],
                        name="idx_notif_deliv_queue",
                    ),
                    models.Index(
                        fields=["status", "attempt_count", "last_attempt_at"],
                        name="idx_notif_deliv_retry",
                    ),
                ],
            },
        ),
    ]
