# Generated by Django 5.2.10 on 2026-01-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notificationdelivery_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationdelivery",
            old_name="recipient_type",
            new_name="notification_type",
        ),
    ]
