# Generated by Django 5.2.10 on 2026-01-21 23:08

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Telemetry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "payload",
                    models.JSONField(
                        help_text='Schema: {"version": "0.0.1", "serial_number": "SN123456", "value": 5.2}'
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_data",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Telemetry",
                "db_table": "telemetry",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"], name="idx_telemetry_device_time"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["payload"], name="idx_telemetry_payload_gin"
                    ),
                ],
            },
        ),
    ]
