# Generated by Django 5.2.10 on 2026-02-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
        ("telemetry", "0002_enable_timescaledb_hypertable"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemetrySchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Example: '1.0', '2.0'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "validation_schema",
                    models.JSONField(
                        default=dict,
                        help_text="Official JSON Schema for validating input data structure.",
                    ),
                ),
                (
                    "transformation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Rules for normalizing data. Example: {"rename": {"val": "temperature"}}',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Telemetry Schemas",
                "db_table": "telemetry_schema",
            },
        ),
        migrations.RemoveIndex(
            model_name="telemetry",
            name="idx_telemetry_device_time",
        ),
        migrations.AlterField(
            model_name="telemetry",
            name="payload",
            field=models.JSONField(
                help_text='Schema: {"schema_version": "1.0", "serial_number": "SN123456", "value": 5.2}'
            ),
        ),
        migrations.AddIndex(
            model_name="telemetry",
            index=models.Index(
                fields=["device", "-timestamp"], name="idx_telemetry_device_time"
            ),
        ),
        migrations.AddIndex(
            model_name="telemetry",
            index=models.Index(fields=["-timestamp"], name="idx_telemetry_timestamp"),
        ),
    ]
