# Generated by Django 5.2.10 on 2026-02-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0003_telemetryschema_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telemetryschema",
            name="transformation_rules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Rules for normalizing telemetry data.Example: {"rename": {"val": "temperature"}}',
            ),
        ),
        migrations.AlterField(
            model_name="telemetryschema",
            name="validation_schema",
            field=models.JSONField(
                default=dict,
                help_text="Official JSON Schema for validating incoming telemetry data.",
            ),
        ),
        migrations.AlterField(
            model_name="telemetryschema",
            name="version",
            field=models.CharField(
                help_text="Example: '1.0', '2.0'", max_length=50, unique=True
            ),
        ),
    ]
