# Generated by Django 5.2.10 on 2026-02-22 18:30

import apps.telemetry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0004_alter_telemetryschema_transformation_rules_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telemetryschema",
            name="transformation_rules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Rules for normalizing telemetry data. Example: {"rename": {"val": "temperature"}}',
                validators=[apps.telemetry.models.validate_transformation_rules],
            ),
        ),
        migrations.AlterField(
            model_name="telemetryschema",
            name="validation_schema",
            field=models.JSONField(
                default=dict,
                help_text="Official JSON Schema for validating incoming telemetry data.",
                validators=[apps.telemetry.models.validate_json_schema],
            ),
        ),
    ]
