# Generated by Django 5.2.10 on 2026-01-22 19:09

import apps.events.models
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("rules", "0002_rename_operator_to_comparison_operator"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="event",
            name="idx_event_telemetry",
        ),
        migrations.RemoveField(
            model_name="event",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="event",
            name="telemetry_id",
        ),
        migrations.AddField(
            model_name="event",
            name="telemetry_snapshot",
            field=models.JSONField(
                blank=True,
                help_text='Snapshot of telemetry data that triggered this event. Stored as a copy to avoid orphaned references when telemetry is deleted by retention policy. Expected structure: {"device_id": "uuid", "timestamp": "ISO-8601", "payload": {...}}',
                null=True,
                validators=[apps.events.models.validate_telemetry_snapshot],
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="execution_results",
            field=models.JSONField(
                help_text='Schema: [{"type": "notification", "template_id": 5, "status": "completed", "sent_count": 3, "completed_at": "2025-01-21T10:00:08Z"}, {"type": "stop_machine", "machine_id": "M-123", "status": "failed", "error": "API timeout"}]',
                validators=[apps.events.models.validate_execution_results],
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["telemetry_snapshot"], name="idx_event_telemetry_snap_gin"
            ),
        ),
    ]
