# Generated by Django 5.2.10 on 2026-02-24 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_execution_results"),
        ("rules", "0006_alter_rule_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="external_rule_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="rules.rule",
            ),
        ),
    ]
