openapi: 3.0.3
info:
  title: Industry 4.0 IoT
  version: 1.0.0
  contact:
    name: "Api Owner"
    url: "http://www.example-industry.com"
    email: "support@idustry.com"
  description: IoT Service for industrial use
tags:
  - name: devices
    description: Devices reporting telemetry data
  - name: telemetry
    description: Telemetry ingestion and retrieval
  - name: auth
    description: Authentication control
security:
  - BearerAuth: []
servers:
  - url: /api/v1
paths:
  /telemetry:
    get:
      description: get telemetry data
      summary: Get paginated telemetry data
      operationId: TelemetryList
      tags: [telemetry]
      parameters:
        - $ref: "#/components/parameters/PageParam"
        - $ref: "#/components/parameters/PageSizeParam"
        - name: device_id
          in: query
          description: Get telemetry data of specific device by id
          schema:
            type: string
          example: a1b2c3d4-e5f6-7890-1234-567890abcdef
      responses:
        "200":
          description: Page of telemetry data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TelemetryListResponse"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    post:
      security: []
      description: Submit telemetry data to ingest
      summary: Ingest for telemetry collection
      operationId: TelemetrySubmit
      tags: [telemetry]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TelemetryPost"
      responses:
        "202":
          description: Telemetry accepted for processing
        "400":
          $ref: "#/components/responses/BadRequest"
  /devices:
    get:
      description: get list of devices
      summary: Get paginated device data
      operationId: DeviceList
      tags: [devices]
      parameters:
        - $ref: "#/components/parameters/PageParam"
        - $ref: "#/components/parameters/PageSizeParam"
      responses:
        "200":
          description: a paginated list of all devices
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeviceListResponse"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    post:
      description: create a new device
      summary: Create a new device
      operationId: DeviceSubmit
      tags: [devices]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceCreate"
      responses:
        "201":
          description: device created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Devices"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
  /devices/{id}:
    get:
      description: get a specific deviced by id
      summary: Get a specific device based on id in url paths
      operationId: DeviceGet
      tags: [devices]
      parameters:
        - name: id
          in: path
          required: true
          description: Get telemetry data of specific device by id
          schema:
            type: string
            example: a1b2c3d4-e5f6-7890-1234-567890abcdef
      responses:
        "200":
          description: device information by id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Devices"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
  /auth/fake:
    get: 
      security: []
      description: Fake JWT token
      summary: Obtain a test token
      operationId: TokenFake
      tags: [auth]
      responses:
        "200":
          description: get a fake token
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/FakeToken"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    PageParam:
      name: page
      in: query
      description: Page number (1-based)
      schema:
        type: integer
        minimum: 1
      example: 1
    PageSizeParam:
      name: page_size
      in: query
      description: Number of items per page
      schema:
        type: integer
        minimum: 1
        maximum: 1000
      example: 10
  schemas:
    PaginationMeta:
      type: object
      required: [page, page_size, total, total_pages, next_page, prev_page]
      properties:
        page:
          type: integer
          example: 2
        page_size:
          type: integer
          example: 10
        total:
          type: integer
          description: Total number of items matching the query
          example: 134
        total_pages:
          type: integer
          description: Total pages available (derived from total/page_size)
          example: 14
        next_page:
          type: integer
          nullable: true
          description: Next page number if available, otherwise null
          example: 3
        prev_page:
          type: integer
          nullable: true
          description: Previous page number if available, otherwise null
          example: 1
    TelemetryListResponse:
      type: object
      required: [data, pagination]
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/Telemetry"
        pagination:
          $ref: "#/components/schemas/PaginationMeta"
    DeviceListResponse:
      type: object
      required: [data, pagination]
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/Devices"
        pagination:
          $ref: "#/components/schemas/PaginationMeta"
    Error:
      type: object
      required: [error]
      properties:
        error:
          type: string
          example: Some error has occured
    FakeToken:
      type: object
      required: [fakejwt]
      properties: 
        fakejwt:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE3MTYyMzkwMjJ9.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    Telemetry:
      type: object
      required:
        - ssn
        - value
        - metric
        - ts
      properties:
        ssn:
          type: string
          example: SN2224412
        value:
          type: integer
          example: 2432
        metric:
          type: string
          example: C
        ts:
          type: string
          format: date-time
          example: "2026-01-16T22:53:00Z"
    TelemetryPost:
      type: object
      required:
        - ssn
        - value
      properties:
        schema_version:
          type: string
          description: Telemetry payload schema version
          example: "1.0"
        ssn:
          type: string
          example: SN222443
        value:
          type: integer
          example: 2443
    Devices:
      type: object
      required:
        - name
        - ssn
        - location
        - status
        - created
        - updated
      properties:
        name:
          type: string
          example: Themometer lower level 5
        ssn:
          type: string
          example: SN2224412
        location:
          type: string
          example: Industrial park 15
        status:
          type: string
          example: Paused
        created:
          type: string
          format: date-time
          example: 2026-01-16T14:30:00Z
        updated:
          type: string
          format: date-time
          example: 2026-01-16T17:30:00Z
    DeviceCreate:
      type: object
      required:
        - name
        - ssn
        - location
        - status
        - description
        - default_metrics
      properties:
        name:
          type: string
          example: Themometer lower level 5
        ssn:
          type: string
          example: SN2224412
        location:
          type: string
          example: Industrial park 15
        status:
          type: string
          example: Paused
        description:
          type: string
          example: Gen 2 Themometer
        default_metrics:
          type: string
          example: C
  responses:
    UnauthorizedError:
      description: No or invalid JWT token provided
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    NotFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    BadRequest:
      description: Bad request body
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"