openapi: 3.0.3
info:
  title: IoT Catalog Hub API
  version: 0.1.0
  description: Minimal OpenAPI spec for CI validation.
  contact:
    name: IoT Hub API Team
    email: api@example.com
servers:
  - url: http://localhost:8000
paths:
  /healthz:
    get:
      summary: Health check
      description: Returns a basic health status for the service.
      operationId: getHealthz
      tags:
        - Health
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                required:
                  - status
